### ISSUE TITLE
Canvas2prairielearn raises 401 client error

### ISSUE THREAD

**Issue by firasm** [UBC-CS/canvasgrading#6]
hello!

I thought I'd give the `canvas2prairielearn` script a shot and I'm trying to use it like so:

```
python canvas2prairielearn.py -d -t 1122_rest_of_my_token -c 0000000 -q 00000 "full/path/to/pl-ubc-data301" 2022WT1
```

But I'm getting this error:

```
Reading data from Canvas...
Traceback (most recent call last):
  File "/Users/firasm/Sync/Teaching/workflows/canvas_to_prairielearn/canvasgrading/canvas2prairielearn.py", line 35, in <module>
    course = canvas.course(args.course, prompt_if_needed=True)
  File "/Users/firasm/Sync/Teaching/workflows/canvas_to_prairielearn/canvasgrading/canvas.py", line 107, in course
    for course in self.request(f'/courses/{course_id}?include[]=term'):
  File "/Users/firasm/Sync/Teaching/workflows/canvas_to_prairielearn/canvasgrading/canvas.py", line 58, in request
    response.raise_for_status()
  File "/Users/firasm/.pyenv/versions/3.10.2/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://canvas.ubc.ca/api/v1/courses/100277?include%5B%5D=term
```

Has anyone used this script in the recent past and know how to get around this?

Thanks,

Firas

P.S. If it's important, I just generated an access Token from Canvas> Account> Settings.

**Comment by jonatanschroeder** [comment]
There is a slightly newer version of this script in https://github.com/PrairieLearn/PrairieLearn/tree/master/tools/question_converters/canvas. That one has been more recently tested, has more documentation, a slightly better UI, and has support for additional features (e.g., question alternatives). It also uses a config file so you don't need to set the token in the command-line.

That said, I'm not sure what would be causing this error. Maybe put your token in quotes (to avoid unexpected shell conversions)? Another thing you can try is to call it without the `-c` or `-q` arguments, to check if your token is working as expected.

**Comment by firasm** [comment]
Aha! Thanks Jonatan.

I tried the new script with the same token in a json file but got the same error.

Putting quotes around the token also didn't work, so to troubleshoot I just generated a new one (presumably one that didn't have a funny character in it) and that worked just fine! Closing issue.
